# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
ncl <- function(DATA, THETA, CONSTRAINTS, VERBOSEFLAG = FALSE) {
    .Call(`_stIsing_ncl`, DATA, THETA, CONSTRAINTS, VERBOSEFLAG)
}

#' @export
isingGraph <- function(DATA, THETA_INIT, CONSTRAINTS, MAXT, BURN, STEPSIZE, NU, METHODFLAG, VERBOSEFLAG = FALSE) {
    .Call(`_stIsing_isingGraph`, DATA, THETA_INIT, CONSTRAINTS, MAXT, BURN, STEPSIZE, NU, METHODFLAG, VERBOSEFLAG)
}

#'@export
rmultinom_wrapper <- function(prob, classes, batch, K) {
    .Call(`_stIsing_rmultinom_wrapper`, prob, classes, batch, K)
}

#' @export
sampleH <- function(THETA, DATA, CONSTRAINTS, INVERTFLAG = FALSE, VERBOSEFLAG = FALSE) {
    .Call(`_stIsing_sampleH`, THETA, DATA, CONSTRAINTS, INVERTFLAG, VERBOSEFLAG)
}

#' @export
sampleJ <- function(THETA, DATA, CONSTRAINTS, VERBOSEFLAG = FALSE) {
    .Call(`_stIsing_sampleJ`, THETA, DATA, CONSTRAINTS, VERBOSEFLAG)
}

#' @export
sampleVar <- function(THETA, DATA, CONSTRAINTS, NU, METHOD, RANGE, TOTFLAG, PRINTFLAG) {
    .Call(`_stIsing_sampleVar`, THETA, DATA, CONSTRAINTS, NU, METHOD, RANGE, TOTFLAG, PRINTFLAG)
}

